deployment:
  tasks:
    - export DEPLOYPATH=/home/cttiac/public_html/
    - /bin/cp -R /public/admin $DEPLOYPATH
    - /bin/cp -R /public/assets $DEPLOYPATH
    - /bin/cp -R /public/css $DEPLOYPATH
    - /bin/cp -R /public/images $DEPLOYPATH
    - /bin/cp -R /public/js $DEPLOYPATH
    - /bin/cp -R /public/webfonts $DEPLOYPATH
    - /bin/cp /public/index.php $DEPLOYPATH
    

    